// ==UserScript==
// @name		BaldyBot
// @namespace	xmods
// @version		1.0
// @description	POXEL.IO Cheats
// @match		*://*.poxel.io/*
// @run-at		document-start
// @grant		none
// ==/UserScript==
const cfg={vertexCount:192,depthCut:0},WebGL=WebGL2RenderingContext.prototype;HTMLCanvasElement.prototype.getContext=new Proxy(HTMLCanvasElement.prototype.getContext,{apply(t,e,n){return n[1]&&(n[1].preserveDrawingBuffer=!0,n[1].antialias=!1,n[1].powerPreference="high-performance"),Reflect.apply(...arguments)}}),WebGL.shaderSource=new Proxy(WebGL.shaderSource,{apply(t,e,n){let[r,o]=n;return o.indexOf("gl_Position")>-1?(o.indexOf("unity_ObjectToWorld")>-1&&console.log("[SOURCE]",t,e,n),r.isPlayerShader=!0,o=o.replace("void main","out float vDepth;\n\t\t\t\tout vec3 vWorldPos;\n\n\t\t\t\tuniform bool uESP;\n\t\t\t\tuniform float uDepthCut;\n\t\t\t\tvoid main").replace(/return;/,"vDepth = gl_Position.z;\n\t\t\t\tvWorldPos = gl_Position.xyz;\n\t\t\t\tif (uESP && vDepth > uDepthCut) { gl_Position.z = 1.0; }\n\t\t\t\t")):o.indexOf("SV_Target0")>-1&&(o=o.replace("void main","in float vDepth;\n\t\t\t\tin vec3 vWorldPos;\n\n\t\t\t\tuniform bool uESP;\n\t\t\t\tuniform float uDepthCut;\n\t\t\t\tvoid main").replace(/return;/,"if (uESP && vDepth > uDepthCut) {\n\t\t\t\t\tSV_Target0 = vec4(1.0, 1.0, 1.0, 0.2);\n\t\t\t\t}")),n[1]=o,Reflect.apply(...arguments)}}),WebGL.attachShader=new Proxy(WebGL.attachShader,{apply(t,e,[n,r]){return r.isPlayerShader&&(console.log("[SHADER]",r),n.isPlayerProgram=!0),Reflect.apply(...arguments)}}),WebGL.getUniformLocation=new Proxy(WebGL.getUniformLocation,{apply(t,e,[n,r]){const o=Reflect.apply(...arguments);return o&&(o.name=r,o.program=n),o}}),WebGL.uniform4fv=new Proxy(WebGL.uniform4fv,{apply(t,e,[n]){const r=n?.name;return"unity_ObjectToWorld"!==r&&"unity_ObjectToWorld[0]"!==r||(n.program.isUIProgram=!0),Reflect.apply(...arguments)}});let names=[];const drawHandler={apply(t,e,n){const r=e.getParameter(e.CURRENT_PROGRAM);r._u||(r._u={esp:e.getUniformLocation(r,"uESP"),depth:e.getUniformLocation(r,"uDepthCut")});const o=n[1],a=r.isPlayerProgram&&o===cfg.vertexCount;a&&!names.includes(r.name)&&(console.log("[DRAW]",{program:r,isPlayerProgram:r.isPlayerProgram,vertexCount:o}),names.push(r.name)),r._u.esp&&e.uniform1i(r._u.esp,a),r._u.depth&&e.uniform1f(r._u.depth,cfg.depthCut),a&&(gl=e);return Reflect.apply(...arguments)}};WebGL.drawElements=new Proxy(WebGL.drawElements,drawHandler),WebGL.drawElementsInstanced=new Proxy(WebGL.drawElementsInstanced,drawHandler);