// ==UserScript==
// @name		BaldyBot
// @namespace	xmods
// @version		1.0
// @description	POXEL.IO Cheats
// @match		*://*.poxel.io/*
// @run-at		document-end
// @grant		none
// ==/UserScript==

const cfg={vertexCount:192,depthCut:0},WebGL=WebGL2RenderingContext.prototype;let curVPMatrix;HTMLCanvasElement.prototype.getContext=new Proxy(HTMLCanvasElement.prototype.getContext,{apply(e,t,r){return r[1]&&(r[1].preserveDrawingBuffer=!0,r[1].antialias=!1,r[1].powerPreference="high-performance"),Reflect.apply(...arguments)}}),WebGL.shaderSource=new Proxy(WebGL.shaderSource,{apply(e,t,r){let[n,o]=r;return o.indexOf("gl_Position")>-1&&(o.indexOf("unity_ObjectToWorld")>-1&&(n.isPlayerShader=!0),o=o.replace("void main","out float vDepth;\n\t\t\t\tout vec3 vWorldPos;\n\t\t\t\tuniform bool uESP;\n\t\t\t\tuniform float uDepthCut;\n\t\t\t\tvoid main").replace(/return;/,"vDepth = gl_Position.z;\n\t\t\t\tvWorldPos = gl_Position.xyz;\n\t\t\t\tif (uESP && vDepth > uDepthCut) { gl_Position.z = 1.0; }\n\t\t\t\t")),r[1]=o,Reflect.apply(...arguments)}}),WebGL.attachShader=new Proxy(WebGL.attachShader,{apply(e,t,[r,n]){return n.isPlayerShader&&(r.isPlayerProgram=!0),Reflect.apply(...arguments)}}),WebGL.getUniformLocation=new Proxy(WebGL.getUniformLocation,{apply(e,t,[r,n]){const o=Reflect.apply(...arguments);return o&&(o.name=n,o.program=r),o}}),WebGL.uniform4fv=new Proxy(WebGL.uniform4fv,{apply(e,t,[r,n]){return r&&n&&(r?.name.endsWith("unity_ObjectToWorld")||r?.name.endsWith("unity_ObjectToWorld[0]"))&&(r.program.isUIProgram=!0),Reflect.apply(...arguments)}});let playerPos=[];const drawHandler={apply(e,t,r){const n=t.getParameter(t.CURRENT_PROGRAM);n._u||(n._u={esp:t.getUniformLocation(n,"uESP"),depth:t.getUniformLocation(n,"uDepthCut")});const o=n.isPlayerProgram&&r[1]===cfg.vertexCount;n._u.esp&&t.uniform1i(n._u.esp,o),n._u.depth&&t.uniform1f(n._u.depth,cfg.depthCut),o&&(gl=t,n._position&&playerPos.push(n._position));return Reflect.apply(...arguments)}};WebGL.drawElements=new Proxy(WebGL.drawElements,drawHandler),WebGL.drawElementsInstanced=new Proxy(WebGL.drawElementsInstanced,drawHandler);