name: Minify JavaScript

on:
  push:
    branches:
      - main
    paths:
      - 'js/*.js'

permissions:
  contents: write

jobs:
  minify-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Terser
        run: npm install -g terser

      - name: Minify JavaScript files
        run: |
          mkdir -p scripts
          for file in js/*.js; do
            filename=$(basename "$file")
            terser "$file" -o "scripts/$filename" --compress --mangle
          done

      - name: Commit & Push minified files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scripts/*.js
          git commit -m "Minified JS on push" || echo "No changes to commit"
          git push
